[package]
name = "kubelet"
version = "0.3.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"
license-file = "../../LICENSE"
description = "A Kubernetes kubelet implementation in Rust"
repository = "https://github.com/deislabs/krustlet"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "webassembly",
    "kubernetes",
]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["kube-native-tls"]
kube-native-tls = ["kube/native-tls", "oci-distribution/native-tls", "reqwest/native-tls"]
rustls-tls = ["kube/rustls-tls", "oci-distribution/rustls-tls", "reqwest/rustls-tls"]
cli = ["structopt"]
docs = ["cli"]

[dependencies]
async-trait = "0.1"
base64 = "0.12.1"
dirs = "2.0"
anyhow = "1.0"
futures = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
hyper = { version = "0.13", default-features = false, features = ["stream"] }
log = "0.4"
reqwest = { version = "0.10", default-features = false, features = ["json", "stream"]}
tokio  = { version = "0.2", features = ["fs", "stream", "macros", "signal"] }
kube = { version= "0.35", default-features = false }
k8s-openapi = { version = "0.8", default-features = false, features = ["v1_17"] }
chrono = { version = "0.4", features = ["serde"] }
structopt = { version = "0.3", features = ["wrap_help"], optional = true }
hostname = "0.3"
native-tls = "0.2"
tokio-tls = "0.3"
thiserror = "1.0"
lazy_static = "1.4"
oci-distribution = { path = "../oci-distribution", version = "0.2", default-features = false }
url = "2.1"
warp = { version = "0.2", features = ['tls'] }
http = "0.2"
rcgen = "0.8"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
reqwest = {version = "0.10", default-features = false }

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
